### PR TITLE
Add keyboard peripheral example with builder

### PR DESCRIPTION
**Pull request by dzervas**

### CODE REVIEW

**Comment by alexmoon** [comment]
Thanks! nrf-softdevice now supports rustc stable, so we can't use any nightly features. Is it possible to rework your `hid` macro to use `macro_rules!` instead?

**Comment by dzervas** [comment]
oh right! `macro_rules!`, I completely forgot about it!

**Comment by alexmoon** [comment]
Thanks! Can you also revert the formatting changes to Cargo.toml?

**Comment by alexmoon** [comment]
I think you still need your `[[bin]]` section? I was just asking you to revert the formatting changes that were unrelated to this PR.

**Comment by dzervas** [comment]
oops, reverted a bit too much!

**Pull request merged**
