### PR TITLE
Add descriptor and attribute value to `gatt_service` proc macro

### PR DESCRIPTION
**Pull request by HaoboGu**
Descriptor and attribute value settings are commonly used in BLE characteristic, with this PR, they can be specified as:

```rust
#[nrf_softdevice::gatt_service(uuid = "1812")]
pub struct HidService {
    #[characteristic(
        uuid = "2A4D",
        read,
        write,
        value = "[0u8, 1u8]",
        descriptor(uuid = "2908", security = "justworks", value = "[0, 1]")
    )]
    pub data: [u8; 1],
```

### CODE REVIEW

**Comment by alexmoon** [comment]
Can you add an example to the examples project demonstrating how this is used?

**Comment by HaoboGu** [comment]
Sure, will do!

**Comment by alexmoon** [comment]
Is it possible to allow multiple descriptors per characteristic by repeating the `descriptor(...)` argument?

**Comment by HaoboGu** [comment]
It might be possible, I'm not sure.. will have a try tomorrow!

**Comment by HaoboGu** [comment]
Multiple descriptor fields is supported. Just tested it, works fine.

**Pull request merged**
