### PR TITLE
Update for `embassy-util` split

### PR DESCRIPTION
**Pull request by quentinmit**
The only sketchy thing is that I had to replace `Forever` with `UnsafeCell<MaybeUninit<_>>` in `softdevice.rs`; that could probably use scrutiny. (Embassy got rid of `Forever` and the replacement `StaticCell` doesn't have a `steal` method.)

### CODE REVIEW

**Comment by lulf** [comment]
@quentinmit I just merged #132 which had a fix for the Forever replacement. Maybe you could update this PR with the remaining changes?

**Comment by quentinmit** [comment]
> @quentinmit I just merged #132 which had a fix for the Forever replacement. Maybe you could update this PR with the remaining changes?

Sure. I'm wondering why you made such massive refactoring changes to the examples as part of that PR - you took a number of multitasking examples and made them sequential.

**Comment by lulf** [comment]
@quentinmit For the record I didn't make the changes, but they still use two async tasks. Instead of having cortex-m-rt main create the executor and spawn two tasks, now they use the macros which under the hood spawns the main task, which in turn spawns the sd task. So it's the same number of async tasks, but IMHO more readable.

**Comment by quentinmit** [comment]
> @quentinmit For the record I didn't make the changes, but they still use two async tasks. Instead of having cortex-m-rt main create the executor and spawn two tasks, now they use the macros which under the hood spawns the main task, which in turn spawns the sd task. So it's the same number of async tasks, but IMHO more readable.

Oh, sorry, I misparsed and thought you had made the change.

What I meant was e.g. `ble_advertise.rs` went from two tasks (`sd_task` and `bluetooth_task`) to one task (`sd_task`) with `bluetooth_task` getting merged into `main`. That's all I meant. I understand the `embassy_executor::main` attribute macro and I agree that part of the change is a nice simplification.

Since you merged this PR it still contains a ~revert of all of the example changes; I guess you were okay with that? I'm happy to keep any useful simplifications for the examples.

**Comment by Dirbaio** [comment]
> ble_advertise.rs went from two tasks (sd_task and bluetooth_task) to one task (sd_task) with bluetooth_task getting merged into main

`#[embassy::main]` is itself a task, so the examples after my changes still have 2 tasks. Main will still run concurrently with `bluetooth_task`. Behavior is exactly the same.

**Comment by quentinmit** [comment]
> > ble_advertise.rs went from two tasks (sd_task and bluetooth_task) to one task (sd_task) with bluetooth_task getting merged into main
> 
> `#[embassy::main]` is itself a task, so the examples after my changes still have 2 tasks. Main will still run concurrently with `bluetooth_task`. Behavior is exactly the same.

Yeah, I just find it less readable to mix the "spawning" work of a typical `main` with the functional code of `bluetooth_task`, especially for an example.

**Comment by lulf** [comment]
I've reverted this PR now. @quentinmit I'm sorry I didn't notice that it had the examples changed, I only saw it changed the crate split, that's my bad. As I argued in my earlier comment, I think the purpose is to show the logic of the BLE usage, not how tasks interact or how the executor work, that is anyway shown more clearly in embassy itself IMO.

**Comment by quentinmit** [comment]
> I've reverted this PR now. @quentinmit I'm sorry I didn't notice that it had the examples changed, I only saw it changed the crate split, that's my bad. As I argued in my earlier comment, I think the purpose is to show the logic of the BLE usage, not how tasks interact or how the executor work, that is anyway shown more clearly in embassy itself IMO.

Let me take a stab at merging the example changes and see if I can come up with something that feels like it preserves both simplicity and readability. I guess I have to open another PR for this branch now that you've reverted it?

**Comment by lulf** [comment]
@quentinmit Yes, please open another PR if you have additional proposed changes. The first commit fixing the split is still present in the master branch btw, so it works with latest embassy.

**Pull request merged**
