### PR TITLE
Fix panic on write with bad length

### LINKED ISSUE #100: gatt: Panics when receiving writes with bad length
How to reproduce:
- Create a writable char of type `u8`.
- Connect to the device with nRF Connect, write an empty value to it.

I have no idea why this happens.

there's this `vlen` attr (for "variable length") https://github.com/embassy-rs/nrf-softdevice/blob/master/nrf-softdevice/src/ble/gatt_server.rs#L21
it's `false` if MIN_LEN==MAX_LEN: https://github.com/embassy-rs/nrf-softdevice/blob/master/nrf-softdevice-macro/src/lib.rs#L246
which is the case for something like `u8` https://github.com/embassy-rs/nrf-softdevice/blob/master/nrf-softdevice/src/ble/gatt_traits.rs#L39-L40

So either I'm misunderstanding what `vlen` does, or there's some bug somewhere (in our code or in the softdevice??)

### PR DESCRIPTION
**Pull request by alexmoon**
Fixes #100 for services generated with the `gatt_service` macro.

### CODE REVIEW

**Comment by Dirbaio** [comment]
This will skip reporting the write event to user code, but the write still goes through (the value gets updated in the GATT server).

This means you can still get the crash if you do `.get_foo()` in the server later, because it'll call `from_gatt()` on the value with the wrong length.

**Comment by Dirbaio** [comment]
> an under-length write will update the first n bytes of the value

Ooh interesting! I didn't know this. Weird.

> Perhaps instead of ignoring the write the service should read the characteristic value from the softdevice when the length is less than min.

Maybe! One possible issue is, if 2 writes happened and you pop the 2 events later, the get() when procesing the 1st event will already see the data from the 2nd write... (unless the softdevice does weird stuff like "applying" the write only when you pop the event?).

So, I guess we can pick between "broken behavior A, or "broken behavior B". Yay.

**Comment by alexmoon** [comment]
Yeah, there can be a race condition in that case, but I think that's an edge case of an edge case. If you need more specific handling, you can easily implement the service yourself instead of using the macro.

**Review by Dirbaio — APPROVED** [review]
Sounds good! LGTMm then

**Pull request merged**
